---
- name: Create grafana config volume
  community.docker.docker_volume:
    name: "{{ app_grafana_docker_volume_config }}"

- name: Create grafana data volume
  community.docker.docker_volume:
    name: "{{ app_grafana_docker_volume_data }}"

- name: Ensure grafana image is pulled
  community.docker.docker_image:
    name: "{{ app_grafana_docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove grafana container
  community.docker.docker_container:
    name: "{{ app_grafana_docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on grafana container
  community.docker.docker_container_info:
    name: "{{ app_grafana_docker_container }}"
  register: result

- name: Create grafana container
  community.docker.docker_container:
    image: "{{ app_grafana_docker_image }}"
    mounts:
     - source: "{{ app_grafana_docker_volume_config }}"
       target: /etc/grafana
     - source: "{{ app_grafana_docker_volume_data }}"
       target: /var/lib/grafana
    name: "{{ app_grafana_docker_container }}"
    networks:
     - name: "{{ app_grafana_docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false

- name: Create tmp grafana directorys
  ansible.builtin.file:
    path: "{{ app_grafana_tmp_dir }}/{{ item }}"
    state: directory
  with_items:
    - "config/provisioning/datasources"
    - "config/provisioning/dashboards"
    - "data/dashboards"
  when:
    result.exists == false

- name: Copy grafana datasources providers
  ansible.builtin.template:
    src: "config/provisioning/datasources/{{ item }}.yaml.j2"
    dest: "{{ app_grafana_tmp_dir }}/config/provisioning/datasources/{{ item }}.yaml"
  with_items:
    - "prometheus"
    - "loki"
  when:
    result.exists == false

- name: Copy grafana dashboard providers
  ansible.builtin.copy:
    src: "config/provisioning/dashboards/"
    dest: "{{ app_grafana_tmp_dir }}/config/provisioning/dashboards/"
  when:
    result.exists == false

- name: Copy grafana dashboard data
  ansible.builtin.copy:
    src: "data/dashboards/"
    dest: "{{ app_grafana_tmp_dir }}/data/dashboards/"
  when:
    result.exists == false

- name: Copy grafana config
  ansible.builtin.template:
    src: "grafana.ini.j2"
    dest: "{{ app_grafana_tmp_dir }}/config/grafana.ini"
  when:
    result.exists == false

- name: Copy config files into grafana container
  shell: docker cp {{ app_grafana_tmp_dir }}/config/. grafana:/etc/grafana
  when:
    result.exists == false

- name: Copy data files into grafana container
  shell: docker cp {{ app_grafana_tmp_dir }}/data/. grafana:/var/lib/grafana
  when:
    result.exists == false

- name: Remove tmp grafana directory
  ansible.builtin.file:
    path: "{{ app_grafana_tmp_dir }}"
    state: absent
  when:
    result.exists == false

- name: Restart grafana container
  community.docker.docker_container:
    name: "{{ app_grafana_docker_container }}"
    restart: yes
  when:
    result.exists == false
