---
- name: Create grafana config volume
  community.docker.docker_volume:
    name: grafana_config

- name: Create grafana data volume
  community.docker.docker_volume:
    name: grafana_data

- name: Ensure grafana/grafana-enterprise image is pulled
  community.docker.docker_image:
    name: docker.io/grafana/grafana-enterprise
    source: pull
    force_source: yes
  register: pulled

- name: Remove grafana container
  community.docker.docker_container:
    name: grafana
    state: absent
  when: pulled.changed

- name: Get infos on grafana container
  community.docker.docker_container_info:
    name: grafana
  register: result

- name: Create grafana container
  community.docker.docker_container:
    image: docker.io/grafana/grafana-enterprise
    mounts:
     - source: grafana_config
       target: /etc/grafana
     - source: grafana_data
       target: /var/lib/grafana
    name: grafana
    networks:
     - name: app-network
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
